/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.w3c.flute.parser;

public interface ParserConstants {

  int EOF = 0;
  int S = 1;
  int CDO = 5;
  int CDC = 6;
  int LBRACE = 7;
  int RBRACE = 8;
  int DASHMATCH = 9;
  int INCLUDES = 10;
  int EQ = 11;
  int PLUS = 12;
  int MINUS = 13;
  int COMMA = 14;
  int SEMICOLON = 15;
  int PRECEDES = 16;
  int DIV = 17;
  int LBRACKET = 18;
  int RBRACKET = 19;
  int ANY = 20;
  int DOT = 21;
  int LPARAN = 22;
  int RPARAN = 23;
  int COLON = 24;
  int NONASCII = 25;
  int H = 26;
  int UNICODE = 27;
  int ESCAPE = 28;
  int NMSTART = 29;
  int NMCHAR = 30;
  int STRINGCHAR = 31;
  int D = 32;
  int NAME = 33;
  int STRING = 34;
  int IDENT = 35;
  int NUMBER = 36;
  int _URL = 37;
  int URL = 38;
  int PERCENTAGE = 39;
  int PT = 40;
  int MM = 41;
  int CM = 42;
  int PC = 43;
  int IN = 44;
  int PX = 45;
  int EMS = 46;
  int EXS = 47;
  int DEG = 48;
  int RAD = 49;
  int GRAD = 50;
  int MS = 51;
  int SECOND = 52;
  int HZ = 53;
  int KHZ = 54;
  int DIMEN = 55;
  int HASH = 56;
  int IMPORT_SYM = 57;
  int MEDIA_SYM = 58;
  int CHARSET_SYM = 59;
  int PAGE_SYM = 60;
  int FONT_FACE_SYM = 61;
  int ATKEYWORD = 62;
  int IMPORTANT_SYM = 63;
  int RANGE0 = 64;
  int RANGE1 = 65;
  int RANGE2 = 66;
  int RANGE3 = 67;
  int RANGE4 = 68;
  int RANGE5 = 69;
  int RANGE6 = 70;
  int RANGE = 71;
  int UNI = 72;
  int UNICODERANGE = 73;
  int FUNCTION = 74;
  int UNKNOWN = 75;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 4>",
    "\"<!--\"",
    "\"-->\"",
    "\"{\"",
    "\"}\"",
    "\"|=\"",
    "\"~=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\";\"",
    "\">\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\".\"",
    "\")\"",
    "\"(\"",
    "\":\"",
    "<NONASCII>",
    "<H>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRINGCHAR>",
    "<D>",
    "<NAME>",
    "<STRING>",
    "<IDENT>",
    "<NUMBER>",
    "<_URL>",
    "<URL>",
    "<PERCENTAGE>",
    "<PT>",
    "<MM>",
    "<CM>",
    "<PC>",
    "<IN>",
    "<PX>",
    "<EMS>",
    "<EXS>",
    "<DEG>",
    "<RAD>",
    "<GRAD>",
    "<MS>",
    "<SECOND>",
    "<HZ>",
    "<KHZ>",
    "<DIMEN>",
    "<HASH>",
    "\"@import\"",
    "\"@media\"",
    "\"@charset\"",
    "\"@page\"",
    "\"@font-face\"",
    "<ATKEYWORD>",
    "<IMPORTANT_SYM>",
    "<RANGE0>",
    "<RANGE1>",
    "<RANGE2>",
    "<RANGE3>",
    "<RANGE4>",
    "<RANGE5>",
    "<RANGE6>",
    "<RANGE>",
    "<UNI>",
    "<UNICODERANGE>",
    "<FUNCTION>",
    "<UNKNOWN>",
  };

}
