/*****************************************************************************
 * Copyright (C) The Apache Software Foundation. All rights reserved.        *
 * ------------------------------------------------------------------------- *
 * This software is published under the terms of the Apache Software License *
 * version 1.1, a copy of which has been included with this distribution in  *
 * the LICENSE file.                                                         *
 *****************************************************************************/

package org.apache.batik.util.awt.geom;

import java.awt.geom.AffineTransform;

/**
 * This class allows lazy computation of an <tt>AffineTransform</tt>
 *
 * @author <a href="mailto:vincent.hardy@eng.sun.com">Vincent Hardy</a>
 * @version $Id$
 */
public interface AffineTransformSource extends Cloneable{
    /**
     * @returns AffineTransform generated by this source
     */
    public AffineTransform getTransform();

    public Object clone();
}

