/*****************************************************************************
 * Copyright (C) The Apache Software Foundation. All rights reserved.        *
 * ------------------------------------------------------------------------- *
 * This software is published under the terms of the Apache Software License *
 * version 1.1, a copy of which has been included with this distribution in  *
 * the LICENSE file.                                                         *
 *****************************************************************************/

package org.apache.batik.util.awt.geom;

import java.awt.geom.AffineTransform;

/**
 * No-op <tt>AffineTransformSource</tt>
 *
 * @author <a href="mailto:vincent.hardy@eng.sun.com">Vincent Hardy</a>
 * @version $Id$
 */
public class DefaultAffineTransformSource implements AffineTransformSource {
    private AffineTransform txf;

    /**
     * @param transoform transform for this source
     */
    public DefaultAffineTransformSource(AffineTransform txf){
        this.txf = txf;
    }

    /**
     * @returns AffineTransform generated by this source
     */
    public AffineTransform getTransform(){
        return txf;
    }

    public Object clone(){
        return new DefaultAffineTransformSource(txf);
    }
}

